name: Backend CI

on:
   push:
    branches: [ main ]
   pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Build Docker image
      run: |
        docker build -t ${{ github.event.repository.name }}:${{ github.sha }} .